export { default as LandingPage } from './LandingPage';
export { default as FeaturesPage } from './FeaturesPage';
export { default as PricingPage } from './PricingPage';
export { default as LegalPage } from './LegalPage';
export { default as PrivacyPage } from './PrivacyPage';
export { default as TermsPage } from './TermsPage';
export { default as CookiesPage } from './CookiesPage';
export { default as DemoPage } from './DemoPage';
export { default as ProfilePage } from './ProfilePage';
